sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - sample/node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g @angular/cli
before_script:
  - npm prune
script:
  - npm run build
  - cd sample
  - ng build
after_success:
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
